### ISSUE TITLE
Wrong VIN/connection issue

### ISSUE THREAD

**Issue by fiorrr** [dschablowsky/FordPassWidget#1]
Log:
2020-12-03 19:53:49: FM: read local data
2020-12-03 19:53:49: FP: Fetch data from server
2020-12-03 19:53:50: {"$id":"1","status":401,"version":"1.0.0"}
2020-12-03 19:53:50: Fehler: Falsche VIN oder Verbindungsproblem
2020-12-03 19:53:50: FM: read local data
2020-12-03 19:53:50: null

Username/password and VIN are entered correctly.

**Comment by dschablowsky** [comment]
Which ford app are you using on your smartphone?

**Comment by fiorrr** [comment]
Using the latest version of FordPass 3.13.1 and it is up to date on information.
![0FDEAFF1-940E-4FD2-8016-ECC435D9AD01](https://user-images.githubusercontent.com/311710/101396948-524a0a80-38cc-11eb-85ce-62f31adbc04d.png)

**Comment by dschablowsky** [comment]
Bitte schreib mich direkt unter dschablowsky.dev@gmail.com an, dann kann ich dir eine Debug Version zukommen lassen. Da sollte ich mehr Informationen rausbekommen

**Comment by ollyfr** [comment]
Hallo Damian

Hier meine Mail

Oliver@fischer-me.de

Mit freundlichen Grüssen
Oliver Fischer
Am 9. Dez. 2020, 11:58 +0100 schrieb Damian Schablowsky <notifications@github.com>:

**Comment by dschablowsky** [comment]
> Hallo Damian Hier meine Mail Oliver@fischer-me.de Mit freundlichen Grüssen Oliver Fischer Am 9. Dez. 2020, 11:58 +0100 schrieb Damian Schablowsky <notifications@github.com>:
> […](#)
> Bitte schreib mich direkt unter ***@***.*** an, dann kann ich dir eine Debug Version zukommen lassen. Da sollte ich mehr Informationen rausbekommen — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi Oliver,
die Nachricht war an @fiorrr gerichtet. Ich habe eben für dich eine neue Version (1.0.1) commited, welche die Schriftgröße des Standortes automatisch anpasst.

**Comment by dschablowsky** [comment]
Das Problem lag am fehlenden Sync Modem. Dadurch war das Auto nicht auf den Ford Servern vorhanden und dem entsprechend wurde bei Anfrage der Daten ein Fehler zurückgegeben.
